# Generated by Django 2.2.5 on 2019-09-24 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='game',
            field=models.ForeignKey(db_column='name', max_length=150, on_delete=django.db.models.deletion.CASCADE, to='games.Games'),
        ),
    ]
