# Generated by Django 2.2.5 on 2019-09-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20190924_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='game',
            field=models.CharField(max_length=150),
        ),
    ]
