# Generated by Django 2.2.5 on 2019-09-24 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20190924_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='games',
            field=models.ForeignKey(max_length=150, on_delete=django.db.models.deletion.CASCADE, to='games.Games'),
        ),
    ]
