# Generated by Django 2.2.5 on 2019-09-24 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20190924_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='games',
            field=models.ForeignKey(blank=True, max_length=150, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.Games'),
        ),
    ]
