# Generated by Django 2.2.5 on 2019-09-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_auto_20190924_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('platform', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('genre', models.CharField(max_length=20)),
                ('publisher', models.CharField(max_length=20)),
                ('NA_Sales', models.FloatField(max_length=5)),
                ('EU_Sales', models.FloatField(max_length=5)),
                ('JP_Sales', models.FloatField(max_length=5)),
                ('Other_Sales', models.FloatField(max_length=5)),
                ('Global_Sales', models.FloatField(max_length=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='sales',
            name='games',
        ),
        migrations.DeleteModel(
            name='Games',
        ),
        migrations.DeleteModel(
            name='Sales',
        ),
    ]
