# Generated by Django 2.2.5 on 2019-09-26 22:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_auto_20190924_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='img',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
        ),
        migrations.AddField(
            model_name='game',
            name='info',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
        ),
    ]
