# Generated by Django 2.2.5 on 2019-09-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_auto_20190927_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='img',
            field=models.CharField(default='None', max_length=10),
        ),
        migrations.AlterField(
            model_name='game',
            name='info',
            field=models.CharField(default='None', max_length=10),
        ),
    ]
