# Generated by Django 2.2.5 on 2019-10-07 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20191005_0116'),
        ('games', '0009_auto_20190927_1815'),
    ]

    operations = [
    ]
